seq = """CTCGCTACCCATAGGATCTATGTAGGGGCATGTCCTCCCGGGAAGATGTATAAAAAGGGTGTGACACTGCTCTTAAGCATGTCCTCTATTAACGGCTATCGTTAGCTTAATACACATCAGTTCCCTAGCGGCACATGCCCCGGTGGAGCTGGGTGGGGAGAGGGGTCCAATCAAGTAAAAGCGAAAGGCTCACCAATCCGGTCAATGTAGATAGCCGATAGGTGGTCCTTTAAAAATACGCCATTTAATACGGTACCAATTACCTATAGAGATGACAACCAGGAATTAGCACCCAGCTTGGTGATAAGTGAGTGTTTTCAACATGCATGCTGAGTGCGTCTTAATGCGTGTTATGGGTTAGACTGGGTTCGAAATCTTAGGGTTTCGCTAACGAATGTAATCACGTACACAGTAAAAAGGCCGCCACTGTGGATCTCTGTGGAGCTCCACTAGGCTCCGAGACGGGCATATTGCATGGTTTAGAGTGAAACCGGAGTGTGAATACAATTATGAGATCCGGGGAGGTATGTGCAATGCTTATTAAATGAGCTACGTATTAGGCTGAATCGCCGAATAGTGGCCTAACGCAGAGCTCAACATCCGAAGCTTGAACCCACTGTAACTGCCTAAGATGACGTGGGTTGCCAGGATATAGAGTGTCCGGGTCATTGTGCTTGTGTAGACAGGCAATTACTGTTGATACTTGCAATAGTGCCCAGCATTACTTTTGGGTATACTCCGTCTGCACGGTGGACGCTACGTGCTTCACGGTGCCGCTACATCAGCCGTCCACGTCGCAGGCGATACCTTCTAGTCATGTATTTAACGTAACACTAAAGATAAGTCTAAATCGCAAAACAGATCTCATAAGCCCTACCAC
"""


nuc_replace = {'A': 'T',
               'T': 'A',
               'C': 'G',
               'G': 'C'}

seq = seq.translate(str.maketrans(nuc_replace))
trans = seq[::-1]
print(trans)
